// L293D H-Bridge 
#define ENGINE_ENABLE D4
#define ENGINE_INPUT_1 D5
#define ENGINE_INPUT_2 D6

// SG90 Micro servo
#define SERVO_INPUT D1

// Settings
#define MIN_ENGINE_SPEED 300
#define SPEED_STEP 5
#define START_SERVO_DEGREES 90
#define MAX_SERVO_DEGREES 135
#define MIN_SERVO_DEGREES 45
