#include <Arduino.h>
#include <IRremoteESP8266.h>
#include <IRrecv.h>
#include <IRutils.h>

// L293D H-BRIDGE
#define MAIN_ENGINE_ENABLE D4
#define MAIN_ENGINE_INPUT_1 D5
#define MAIN_ENGINE_INPUT_2 D6

#define TURNING_ENGINE_ENABLE D1
#define TURNING_ENGINE_INPUT_1 D2
#define TURNING_ENGINE_INPUT_2 D0

// IR SENSOR
#define IR_SENSOR D3

// SETTINGS

// MAIN ENGINE
#define MIN_MAIN_ENGINE_SPEED 300
#define MAX_MAIN_ENGINE_SPEED 1000
#define STOP_MAIN_ENGINE_SPEED 200
#define MAIN_ENGINE_SPEED_STEP 100

// TURNING ENGINE
#define MIN_TURNING_ENGINE_SPEED 500
#define MAX_TURNING_ENGINE_SPEED 1000
#define STOP_TURNING_ENGINE_SPEED 0
#define TURNING_ENGINE_SPEED_STEP 500

// IR SENSOR
#define IR_BTN_FORWARD 0xFF629D
#define IR_BTN_BACKWARD 0xFFA857
#define IR_BTN_LEFT 0xFF22DD
#define IR_BTN_RIGHT 0xFFC23D
#define IR_BTN_STOP 0xFF02FD
#define IR_BTN_SENSOR_TOGGLE 0xFF42BD
